name: Auto Merge
on:
  push:
    tags:
      - '*'

jobs:
  merge:
    permissions:
      contents: write
    uses: intisy/workflows/.github/workflows/merge.yml@main
    with:
      source: experimental
      target: stable
      mode: overwrite
