name: Auto Merge
on:
  push:
    tags:
      - '*'

jobs:
  merge:
    permissions:
      contents: write
    uses: Slimefun5/workflows/.github/workflows/auto-merge.yaml@main
    with:
      repository: ${{ github.repository }}
