name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    uses: intisy/workflows/.github/workflows/test.yml@main
    with:
      java_version: '25'
      gradle_test: build -x test
      gradle_args: --no-daemon
    secrets:
      envPAT: ${{ secrets.PAT }}
